name: Hexviewer Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run XCTest Hexviewer Suite
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Latest Stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Run Unit Tests
        env:
          NSUnbufferedIO: YES
        run: |
          set -o pipefail
          xcodebuild \
            -project ReDyne/ReDyne.xcodeproj \
            -scheme ReDyne \
            -destination "platform=iOS Simulator,OS=latest,name=iPhone 15 Pro" \
            test | xcpretty
