name: iOS 16.0 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build for iOS 16.0
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Build for iOS 16.0
        env:
          SCHEME: ReDyne
          PROJECT: ReDyne/ReDyne.xcodeproj
        run: |
          set -o pipefail
          xcodebuild clean build \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            IPHONEOS_DEPLOYMENT_TARGET=16.0 \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
