name: Build iOS .ipa

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install dependencies
        run: |
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          fi

      - name: Build .ipa for iOS 15+
        env:
          SCHEME: ReDyne
          WORKSPACE: ReDyne/ReDyne.xcodeproj/project.xcworkspace
          EXPORT_OPTIONS_PLIST: exportOptions.plist
        run: |
          # Generate exportOptions.plist
          cat > $EXPORT_OPTIONS_PLIST <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>destination</key>
            <string>export</string>
            <key>iCloudContainerEnvironment</key>
            <string>Development</string>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          # Clean build folder
          xcodebuild clean -workspace "$WORKSPACE" -scheme "$SCHEME"

          # Build and archive
          xcodebuild archive \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -sdk iphoneos \
            -archivePath $RUNNER_TEMP/build/ReDyne.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=15.0'

          # Export .ipa
          xcodebuild -exportArchive \
            -archivePath $RUNNER_TEMP/build/ReDyne.xcarchive \
            -exportOptionsPlist $EXPORT_OPTIONS_PLIST \
            -exportPath $RUNNER_TEMP/build

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReDyne.ipa
          path: ${{ runner.temp }}/build/*.ipa
